### ISSUE TITLE
Can't show architecture in nestjs monorepo structure

### ISSUE THREAD

**Issue by bolshchikov** [ArchSense/archsense-mono#26]

**Comment by Bassadin** [comment]
I'd love to be able to choose the starting directory for our monorepo structure as well :)

**Comment by kamranarshid** [comment]
Not able to show architecture in vscode by given command

**Comment by bolshchikov** [comment]
> Not able to show architecture in vscode by given command

Can you please share the structure of the project where you are trying to run the command? Is it a mono-repo?

**Comment by kamranarshid** [comment]
Using  **Show architecture** command.  No its not mono, it is specific repo for one service.

**Comment by bolshchikov** [comment]
> Using **Show architecture** command. No its not mono, it is specific repo for one service.

In that case can you please a) open a separate issue, b) paste the print screen of your project file structure from VSCode panel

**Comment by bolshchikov** [comment]
Can't reproduce
